---
# Authorization Policy for Content Service
# Frontend restricted to /api/* only, other services unrestricted
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: content-service-authz
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: content
  action: ALLOW
  rules:
  # Frontend can only access /api/* routes
  - from:
    - source:
        principals: ["cluster.local/ns/{{ .Release.Namespace }}/sa/g11-frontend"]
    to:
    - operation:
        paths: ["/api/*"]
---
# Authorization Policy for Category Service
# Frontend restricted to /api/* only, other services unrestricted
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: category-service-authz
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: category
  action: ALLOW
  rules:
  # Frontend can only access /api/* routes
  - from:
    - source:
        principals: ["cluster.local/ns/{{ .Release.Namespace }}/sa/g11-frontend"]
    to:
    - operation:
        paths: ["/api/*"]
  # Other services have unrestricted access
  - from:
    - source:
        principals: ["cluster.local/ns/{{ .Release.Namespace }}/sa/g11-content"]
---
# Authorization Policy for User Service
# Frontend restricted to /api/* only, other services unrestricted
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: user-service-authz
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: user
  action: ALLOW
  rules:
  # Frontend can only access /api/* routes
  - from:
    - source:
        principals: ["cluster.local/ns/{{ .Release.Namespace }}/sa/g11-frontend"]
    to:
    - operation:
        paths: ["/api/*"]
  # Other services have unrestricted access
  - from:
    - source:
        principals: 
        - "cluster.local/ns/{{ .Release.Namespace }}/sa/g11-content"
        - "cluster.local/ns/{{ .Release.Namespace }}/sa/g11-category"
