---
{{- if and .Values.gateway.tls.enabled .Values.gateway.tls.acme.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: g11blog-tls
  namespace: {{ .Values.gateway.tls.gatewayNamespace }}
spec:
  secretName: {{ .Values.gateway.tls.secretName }}
  renewBefore: {{ .Values.gateway.tls.acme.renewBefore }}
  commonName: {{ .Values.gateway.hostname }}
  dnsNames:
    - {{ .Values.gateway.hostname }}
  issuerRef:
    name: {{ .Values.gateway.tls.acme.issuerName }}
    kind: {{ .Values.gateway.tls.acme.issuerKind }}
{{- end }}
