---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "g11.fullname" . }}
spec:
  selector:
    istio: {{ .Values.gateway.selector }}
  servers:
    - port:
        number: {{ .Values.gateway.port }}
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.gateway.hostname }}
    {{- if .Values.gateway.tls.enabled }}
    - port:
        number: {{ .Values.gateway.httpsPort }}
        name: https
        protocol: HTTPS
      hosts:
        - {{ .Values.gateway.hostname }}
      tls:
        mode: SIMPLE
        credentialName: {{ include "g11.fullname" . }}-tls
    {{- end }}
