---
apiVersion: v1
kind: Service
metadata:
  name: category
  labels:
    app: category
    service: category
spec:
  ports:
  - port: 3004
    name: http
  selector:
    app: category
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: g11-category
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: category
  labels:
    app: category
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: category
  template:
    metadata:
      labels:
        app: category
    spec:
      serviceAccountName: g11-category
      containers:
      - name: category
        image: jasonmishi/g11-category-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          valueFrom: { secretKeyRef: { name: hippo-postgres-pguser-categorydbuser, key: uri } }
        - name: NODE_ENV
          value: 'production'
        ports:
        - containerPort: 3004
  strategy:
    canary:
      canaryService: category-canary
      stableService: category
      trafficRouting:
        istio:
          virtualServices:
          - name: category-internal
            routes:
            - primary
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 40
      - pause: {duration: 30s}
      - setWeight: 60
      - pause: {duration: 30s}
      - setWeight: 80
      - pause: {duration: 30s}
---
apiVersion: v1
kind: Service
metadata:
  name: category-canary
  labels:
    app: category
    service: category
spec:
  ports:
  - port: 3004
    name: http
  selector:
    app: category
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: category-internal
spec:
  hosts:
  - category
  http:
  - name: primary
    route:
    - destination:
        host: category
        port:
          number: 3004
      weight: 100
    - destination:
        host: category-canary
        port:
          number: 3004
      weight: 0
