---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
    service: user
spec:
  ports:
  - port: 3001
    name: http
  selector:
    app: user
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: g11-user
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      serviceAccountName: g11-user
      containers:
      - name: user
        image: jasonmishi/g11-user-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          valueFrom: { secretKeyRef: { name: hippo-postgres-pguser-userdbuser, key: uri } }
        - name: NODE_ENV
          value: 'production'
        - name: ASGARDEO_ORG_NAME
          value: 'g11engineering'
        - name: ASGARDEO_CLIENT_ID
          value: 'Y4Yrhdn2PcIxQRLfWYDdEycYTfUa'
        - name: ASGARDEO_CLIENT_SECRET
          value: ''
        - name: ASGARDEO_M2M_CLIENT_ID
          value: 'Z4uhhDswzZBUBcJX9caVDFLmys0a'
        - name: ASGARDEO_M2M_CLIENT_SECRET
          value: 'qYv5fgcnc8_rgfsfgEQvkZh1zVZtmXB9gvYNoAw2pnsa'
        ports:
        - containerPort: 3001
  strategy:
    canary:
      canaryService: user-canary
      stableService: user
      trafficRouting:
        istio:
          virtualServices:
          - name: user-internal
            routes:
            - primary
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 40
      - pause: {duration: 30s}
      - setWeight: 60
      - pause: {duration: 30s}
      - setWeight: 80
      - pause: {duration: 30s}
---
apiVersion: v1
kind: Service
metadata:
  name: user-canary
  labels:
    app: user
    service: user
spec:
  ports:
  - port: 3001
    name: http
  selector:
    app: user
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-internal
spec:
  hosts:
  - user
  http:
  - name: primary
    route:
    - destination:
        host: user
        port:
          number: 3001
      weight: 100
