---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
    service: user
spec:
  ports:
  - port: 3001
    name: http
  selector:
    app: user
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: g11-user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-v1
  labels:
    app: user
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      version: v1
  template:
    metadata:
      labels:
        app: user
        version: v1
    spec:
      serviceAccountName: g11-user
      containers:
      - name: user
        image: jasonmishi/g11-user-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          valueFrom: { secretKeyRef: { name: hippo-postgres-pguser-userdbuser, key: uri } }
        - name: NODE_ENV
          value: 'production'
        - name: ASGARDEO_ORG_NAME
          value: 'g11engineering'
        - name: ASGARDEO_CLIENT_ID
          value: 'Y4Yrhdn2PcIxQRLfWYDdEycYTfUa'
        - name: ASGARDEO_CLIENT_SECRET
          value: ''
        - name: ASGARDEO_M2M_CLIENT_ID
          value: 'Z4uhhDswzZBUBcJX9caVDFLmys0a'
        - name: ASGARDEO_M2M_CLIENT_SECRET
          value: 'qYv5fgcnc8_rgfsfgEQvkZh1zVZtmXB9gvYNoAw2pnsa'
        ports:
        - containerPort: 3001
