---
apiVersion: v1
kind: Service
metadata:
  name: content
  labels:
    app: content
    service: content
spec:
  ports:
  - port: 3002
    name: http
  selector:
    app: content
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: g11-content
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-v1
  labels:
    app: content
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content
      version: v1
  template:
    metadata:
      labels:
        app: content
        version: v1
    spec:
      serviceAccountName: g11-content
      containers:
      - name: content
        image: jasonmishi/g11-content-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          valueFrom: { secretKeyRef: { name: hippo-pguser-hippo, key: uri } }
        ports:
        - containerPort: 3002
