---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: g11-frontend
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: frontend-health-check
spec:
  metrics:
  - name: http-check
    provider:
      web:
        url: http://frontend-canary.{{ .Release.Namespace }}.svc.cluster.local:3000
        timeoutSeconds: 5
    successCondition: result.statusCode == 200
    failureLimit: 2
    inconclusiveLimit: 2
    interval: 15s
    count: 5
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: g11-frontend
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        env:
        - name: NEXT_PUBLIC_USER_SERVICE_URL
          value: "http://user:3001"
        - name: NEXT_PUBLIC_CONTENT_SERVICE_URL
          value: "http://content:3002"
        - name: NEXT_PUBLIC_CATEGORY_SERVICE_URL
          value: "http://category:3004"
        - name: NEXT_PUBLIC_ASGARDEO_REDIRECT_URL
          value: "http://localhost:8080"
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
  strategy:
    canary:
      canaryService: frontend-canary
      stableService: frontend
      trafficRouting:
        istio:
          virtualService:
            name: g11blog
            routes:
            - primary
      steps:
      - setWeight: 0
      - pause: {duration: 30s}
      - analysis:
          templates:
          - templateName: frontend-health-check
      - setWeight: 20
      - pause: {duration: 30s}
      - analysis:
          templates:
          - templateName: frontend-health-check
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-canary
  labels:
    app: frontend
    service: frontend
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: frontend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
