---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: g11-frontend
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: frontend-health-check
spec:
  metrics:
  - name: http-check
    provider:
      web:
        url: http://frontend-canary:3000
    successCondition: result.statusCode == 200
    interval: 15s
    count: 3
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: g11-frontend
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        env:
        - name: NEXT_PUBLIC_USER_SERVICE_URL
          value: "http://user:3001"
        - name: NEXT_PUBLIC_CONTENT_SERVICE_URL
          value: "http://content:3002"
        - name: NEXT_PUBLIC_CATEGORY_SERVICE_URL
          value: "http://category:3004"
        - name: NEXT_PUBLIC_FRONTEND_HOST
          value: "localhost"
        - name: NEXT_PUBLIC_FRONTEND_PORT
          value: "8080"
        - name: NEXT_PUBLIC_ASGARDEO_REDIRECT_URL
          value: "http://localhost:8080"
        - name: ASGARDEO_REDIRECT_URL
          value: "http://localhost:8080"
        ports:
        - containerPort: 3000
  strategy:
    canary:
      canaryService: frontend-canary
      stableService: frontend
      trafficRouting:
        istio:
          virtualService:
            name: g11blog
            routes:
            - primary
      analysis:
        templates:
        - templateName: frontend-health-check
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - analysis:
          templates:
          - templateName: frontend-health-check
      - setWeight: 40
      - pause: {duration: 30s}
      - analysis:
          templates:
          - templateName: frontend-health-check
      - setWeight: 60
      - pause: {duration: 30s}
      - analysis:
          templates:
          - templateName: frontend-health-check
      - setWeight: 80
      - pause: {duration: 30s}
      - analysis:
          templates:
          - templateName: frontend-health-check
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-canary
  labels:
    app: frontend
    service: frontend
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: frontend
