---
# Enforces STRICT mTLS for all service-to-service communication
# ArgoCD namespace should have Istio enabled, so health checks will use mTLS
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT
