---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "g11.fullname" . }}
spec:
  hosts:
  - {{ .Values.gateway.hostname }}
  gateways:
  - {{ include "g11.fullname" . }}
  http:
  {{- if .Values.gateway.tls.enabled }}
  - match:
    - uri:
        prefix: /
      scheme:
        exact: http
    redirect:
      scheme: https
      redirectCode: 301
  {{- end }}
  - name: primary
    route:
    - destination:
        host: {{ include "g11.serviceFQDN" (dict "service" "frontend" "context" .) }}
        port:
          number: 3000
      weight: 100
    - destination:
        host: {{ include "g11.serviceFQDN" (dict "service" "frontend-canary" "context" .) }}
        port:
          number: 3000
      weight: 0

