---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: g11blog
spec:
  hosts:
  - {{ .Values.gateway.hostname }}
  gateways:
  - g11blog
  http:
  - name: primary
    route:
    - destination:
        host: frontend
        port:
          number: 3000
      weight: 100
    - destination:
        host: frontend-canary
        port:
          number: 3000
      weight: 0

