---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: g11blog
spec:
  hosts:
  - {{ .Values.gateway.hostname }}
  gateways:
  - g11blog
  http:
    - route:
      - destination:
          host: frontend
          port:
            number: 3000

