apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: g11-kind-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    # Update repoURL / targetRevision if you are demoing from a fork or a branch.
    repoURL: https://github.com/G11-Engineering/g11-helm-charts
    targetRevision: kind-demo-argocd
    path: postgres
    helm:
      releaseName: hippo-postgres
      valueFiles:
        - values-kind.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: g11-kind
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
