apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: "true"
spec:
  image: {{ .Values.postgres.image }}
  postgresVersion: {{ .Values.postgres.version }}

  users:
    - name: userdbuser
      databases:
        - userdb
    - name: contentdbuser
      databases:
        - contentdb
    - name: categorydbuser
      databases:
        - categorydb

  instances:
    - name: {{ .Values.instances.name }}
      dataVolumeClaimSpec:
        accessModes:
        {{- range .Values.instances.dataVolume.accessModes }}
        - "{{ . }}"
        {{- end }}
        {{- if .Values.instances.dataVolume.storageClassName }}
        storageClassName: {{ .Values.instances.dataVolume.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.instances.dataVolume.size }}

  backups:
    pgbackrest:
      image: {{ .Values.backups.pgbackrest.image }}
      repos:
        - name: {{ .Values.backups.pgbackrest.repos.name }}
          volume:
            volumeClaimSpec:
              accessModes:
              {{- range .Values.backups.pgbackrest.repos.dataVolume.accessModes }}
              - "{{ . }}"
              {{- end }}
              {{- if .Values.backups.pgbackrest.repos.dataVolume.storageClassName }}
              storageClassName: {{ .Values.backups.pgbackrest.repos.dataVolume.storageClassName }}
              {{- end }}
              resources:
                requests:
                  storage: {{ .Values.backups.pgbackrest.repos.dataVolume.size }}

