apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: argocd-gateway
  namespace: argocd
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - {{ .Values.gateway.hostname }}
      port:
        name: http
        number: 8082
        protocol: HTTP
      tls:
        httpsRedirect: false
    {{- if .Values.gateway.tls.enabled }}
    - hosts:
        - {{ .Values.gateway.hostname }}
      port:
        name: https
        number: 8445
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.gateway.tls.secretName }}
    {{- end }}

