apiVersion: v2
name: argo-cd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 9.1.6
    repository: https://argoproj.github.io/argo-helm
  - name: argo-rollouts
    version: 2.40.5
    repository: https://argoproj.github.io/argo-helm
  - name: cert-manager
    version: v1.19.2
    repository: oci://quay.io/jetstack/charts
    alias: cert-manager
    condition: cert-manager.enabled

